version: '3.8'
services:
  suggestdb:
    container_name: suggestdb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  suggestai:
    image: suggestai:v0.1
#    restart: always
    container_name: suggestai
    ports:
      - '8080:8080'

  suggestai-engine:
    image: suggestai-engine:v0.1
    container_name: suggestai-engine
    ports:
      - '5001:5001'